"""Lightweight public CLI entrypoint; startup status is not command approval.

The large CLI and service modules deliberately run without generated bytecode.
Their compilation can hold the GIL longer than a heartbeat interval, so the
optional, content-free startup heartbeat uses a separate, stdin-bound process.
Importing this module never starts that process or writes to either stream.
"""

from __future__ import annotations

import sys

from . import __version__


# Public names and defaults only: CI compares this presentation table with
# the actual parser. It grants no capability, argument validity, or approval.
_PROGRESS_COMMANDS = """
abstract-backfill-plan abstract-backfill-receipt-audit abstract-backfill-recover
abstract-backfill-recovery-plan abstract-backfill-revert abstract-backfill-write
abstract-catalog abstract-freshness activity-group-membership-plan
activity-group-membership-recover activity-group-membership-removal-plan
activity-group-membership-removal-recover activity-group-membership-removal-write
activity-group-membership-write ai-start-here canonical-revision-audit
catalog-pass catalog-pass-cleanup catalog-pass-read doctor draft-pipeline-audit
duplicate-object-reconcile duplicate-object-reconciliation
event-group-membership-plan event-group-membership-recover
event-group-membership-removal-plan event-group-membership-removal-recover
event-group-membership-removal-write event-group-membership-write
external-locator-record first-read-freshness first-read-readiness git-backup-plan
git-backup-reconcile-plan inbox-pipeline-audit index index-health memory-readiness
mint-zet mint-zettel notion-import-locator-evidence-plan
notion-import-locator-loss-audit notion-locator-loss-audit
object-storage-adopt-existing object-storage-upload-adopt-existing
objet-capture-batch objet-capture-selection objet-storage-adopt-existing
operator-start-here project-version-update revision-receipt-audit runtime-context
source-intake-batch source-intake-record staged-cleanup-check start-here
title-readiness title-remap-plan title-remap-receipt-audit title-remap-recover
title-remap-recovery-plan title-remap-revert title-remap-revert-plan
title-remap-revert-recover title-remap-revert-recovery-plan title-remap-write
update-wom-kit upgrade-check validate version version-update
zet-abstract-backfill-plan zet-abstract-backfill-receipt-audit
zet-abstract-backfill-recover zet-abstract-backfill-recovery-plan
zet-abstract-backfill-revert zet-abstract-backfill-write zet-abstract-freshness
zet-catalog zet-catalog-drain zet-catalog-pass zet-catalog-pass-cleanup
zet-catalog-pass-read zet-first-readiness zet-objet-link
zet-revision-receipt-audit zet-title-check zet-title-readiness zet-title-remap-plan
zet-title-remap-receipt-audit zet-title-remap-recover zet-title-remap-recovery-plan
zet-title-remap-revert zet-title-remap-revert-plan zet-title-remap-revert-recover
zet-title-remap-revert-recovery-plan zet-title-remap-write zettel-catalog
zettel-objet-link work-session
""".split()
STARTUP_PROGRESS_DEFAULTS = {
    command: command in {"doctor", "source-intake-batch", "objet-capture-batch", "work-session"}
    for command in _PROGRESS_COMMANDS
}
STARTUP_STATUS = "[wom] startup: preparing command\n"
STARTUP_HEARTBEAT = "[wom] startup: still preparing command\n"

# No command arguments, archive path, operation reference, or user text enter
# this program. EOF on the one liveness pipe also ends it after parent death.
_WATCHDOG_PROGRAM = """import os, threading
stop = threading.Event()
def parent_liveness():
    try:
        os.read(0, 1)
    except OSError:
        pass
    finally:
        stop.set()
threading.Thread(target=parent_liveness, daemon=True).start()
while not stop.wait(5.0):
    try:
        os.write(2, b'[wom] startup: still preparing command\\n')
    except OSError:
        break
"""
_active_watchdog: _StartupWatchdog | None = None


def startup_progress_requested(argv: list[str]) -> bool:
    """Select only existing public progress modes, without parsing private data."""
    if not argv or argv[0] not in STARTUP_PROGRESS_DEFAULTS:
        return False
    options = argv[1:]
    if "--" in options:
        options = options[: options.index("--")]
    # When contradictory switches are supplied, be conservatively quiet and
    # let the actual parser retain sole authority over their validity/order.
    if any(option in {"--no-progress", "--help", "-h", "--version"} for option in options):
        return False
    if argv[0] == "git-backup-reconcile-plan" and any(
        option.split("=", 1)[0] in {"--client-app-ref", "--task-route-ref", "--work-session-ref", "--resume"}
        for option in options
    ):
        # The explicit session route owns progress by default, including the
        # heavy CLI import. Inspect fixed option names only, never their values;
        # actual parsing and the original unscoped mode remain unchanged.
        return True
    return bool(STARTUP_PROGRESS_DEFAULTS[argv[0]] or "--progress" in options)


class _StartupWatchdog:
    def __init__(self, process: object) -> None:
        self.process = process
        self.closed = False

    def close(self) -> None:
        """Reap only our child; observation failure cannot change an operation."""
        if self.closed:
            return
        self.closed = True
        import subprocess

        process = self.process
        try:
            if process.stdin is not None:
                process.stdin.close()
        except (OSError, ValueError):
            pass
        try:
            process.wait(timeout=2.0)
            return
        except (OSError, subprocess.TimeoutExpired):
            pass
        for method in (process.terminate, process.kill):
            try:
                method()
                process.wait(timeout=1.0)
                return
            except (OSError, subprocess.TimeoutExpired):
                pass


def _start_startup_progress(argv: list[str]) -> _StartupWatchdog | None:
    if not startup_progress_requested(argv):
        return None
    try:
        sys.stderr.write(STARTUP_STATUS)
        sys.stderr.flush()
    except (OSError, UnicodeError, ValueError):
        return None

    # The first status precedes even the subprocess support imports. Nothing
    # here observes an archive, asks for approval, or writes a progress file.
    import os
    import subprocess

    from .process_launch import noninteractive_creationflags

    environment = {
        key: value
        for key in ("SystemRoot", "WINDIR")
        if (value := os.environ.get(key)) is not None
    }
    try:
        process = subprocess.Popen(
            [sys.executable, "-I", "-B", "-c", _WATCHDOG_PROGRAM],
            stdin=subprocess.PIPE,
            stdout=subprocess.DEVNULL,
            stderr=sys.stderr,
            env=environment,
            close_fds=True,
            creationflags=noninteractive_creationflags(),
        )
    except (OSError, ValueError):
        # Startup progress is best effort, never a new command availability or
        # approval gate. No exception text or private argument is reflected.
        return None
    return _StartupWatchdog(process)


def handoff_startup_progress() -> None:
    """Stop startup output before the first real reporter writes its status."""
    global _active_watchdog
    watchdog = _active_watchdog
    _active_watchdog = None
    if watchdog is not None:
        watchdog.close()


def main(argv: list[str] | None = None) -> int:
    raw_argv = sys.argv[1:] if argv is None else list(argv)
    if raw_argv == ["--version"]:
        # Exactly the existing argparse --version output. Any additional
        # argument still goes through the original parser and its guards.
        print(f"archive {__version__}")
        return 0

    global _active_watchdog
    watchdog = _start_startup_progress(raw_argv)
    _active_watchdog = watchdog
    try:
        from . import archive_cli

        return int(archive_cli.main(raw_argv))
    finally:
        if _active_watchdog is watchdog:
            _active_watchdog = None
        if watchdog is not None:
            watchdog.close()


if __name__ == "__main__":
    # Use the canonical module's registry even under `python -m`: the heavy
    # CLI imports that same module when it hands startup progress over.
    from .cli_entry import main as _canonical_main

    raise SystemExit(_canonical_main())
